[package]
name = "anchor"
version = "0.0.1"
edition = "2021"
description = "Modern 2D Game Framework"
authors = ["Tudor-Cristian Lechintan <lechintantudor02@gmail.com>"]
repository = "https://github.com/LechintanTudor/anchor"
keywords = ["gamedev"]
categories = ["game-development"]
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.21", features = ["bytemuck"] }
glyph_brush = "0.7.5"
image = "0.24"
ordered-float = "3"
pollster = "0.2.5"
rustc-hash = "1.1"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1.9", features = ["const_generics", "const_new", "union"] }
winit = "0.27.3"
wgpu = "0.13.1"
