[package]
name = "anchor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12", features = ["derive"] }
glam = { version = "0.21", features = ["bytemuck"] }
glyph_brush = "0.7.5"
image = "0.24"
log = "0.4"
ordered-float = "3"
pollster = "0.2.5"
rustc-hash = "1.1"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1.9", features = ["const_generics", "const_new", "union"] }
winit = "0.27.3"
wgpu = "0.13.1"
