[package]
name = "anchor"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
glam = { version = "0.21", features = ["bytemuck"] }
glyph_brush = "0.7"
image = "0.24"
log = "0.4"
pollster = "0.2"
old-raw-window-handle = { package = "raw-window-handle", version = "0.4" }
raw-window-handle = "0.5"
ron = "0.7"
rustc-hash = "1.1"
serde = { version = "1", features = ["derive"] }
smallvec = { version = "1.9", features = ["const_generics", "const_new", "union"] }
winit = "0.27"
wgpu = "0.13"
